{
  "props": [],
  "components": {
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 368.0,
      "y": 240.0,
      "props": {
        "path": ".resource",
        "autoSave": "1",
        "trimValues": true,
        "multiLineValues": "1"
      }
    },
    "fileChooserAlt": {
      "type": "script\\FileChooserScript",
      "x": 272.0,
      "y": 144.0,
      "props": {
        "filterName": "Изображение",
        "filterExtensions": "*.png",
        "filterAny": true,
        "inputNode": "",
        "actionNode": ""
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 96.0,
      "y": 128.0,
      "props": {
        "initialDirectory": "",
        "initialFileName": "аа",
        "filterName": "Язык Разметки",
        "filterExtensions": "*.html",
        "filterAny": true,
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}