{
  "props": [],
  "components": {
    "fileChooser3": {
      "type": "script\\FileChooserScript",
      "x": 800.0,
      "y": 304.0,
      "props": {
        "filterName": "Пакет .resource (BundleBuild)",
        "filterExtensions": ".resource",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": ""
      }
    },
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 368,
      "y": 240,
      "props": {
        "path": ".resource",
        "autoSave": "1",
        "trimValues": true,
        "multiLineValues": "1"
      }
    },
    "fileChooserAlt": {
      "type": "script\\FileChooserScript",
      "x": 272,
      "y": 144,
      "props": {
        "filterName": "Изображение",
        "filterExtensions": "*.png",
        "filterAny": true,
        "inputNode": "",
        "actionNode": ""
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 96,
      "y": 128,
      "props": {
        "initialDirectory": "",
        "initialFileName": "аа",
        "filterName": "Язык Разметки",
        "filterExtensions": "*.html",
        "filterAny": true,
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}